### ISSUE TITLE
Enabling distributional setpoints in cooling and thermostat upgrades

### ISSUE THREAD

**Issue by ekpresent** [NREL/resstock#1029]
Applying a distribution in an upgrade isn't possible in YAML logic. There are currently two places I'm aware of where this is a particular challenge. I'd like to see us restructure these two such that we can upgrade to a distribution. 

1. Moving HVAC Uses Cooling from No to Yes. Right now, the cooling setpoint tsv is dependent on the HVAC Uses Cooling characteristic, so changing Uses Cooling from No to Yes, there is no cooling setpoint distribution available. I'd like to see us move to a measure for HVAC Uses Cooling that changes the setpoint to 90 or 95 or 100 or whatever, not a tsv dependency. 

2. Creating new thermostat offsets. Right now, no offset magnitude is assigned to samples with no offset. Assigning a magnitude regardless, that can be turned on, would allow for diversity in offset magnitudes when doing thermostat upgrades. @aspeake set up a limited version of this for the GMLC project run in mid 2022.

**Comment by afontani** [comment]
For #1: I believe is for LA100 ES repository, not the ResStock repository. From @ekpresent (can we use a measure for HVAC Uses cooling instead of a dependency).

Discussion
- Are there other characteristics that could be removed/simplified?
- If "HVAC Uses Cooling" is brought over to develop it should be fed to measure directly rather than changing a septoint.
