### ISSUE TITLE
Remove legacy HPWH options

### ISSUE THREAD

**Issue by jmaguire1** [NREL/resstock#1184]
We have two HPWH options that correspond to 1st generation products (they don't have the UEF called out and have a MUCH lower efficiency than the current generation). Is anyone still using them? Is there any reason to keep them? Right now it seems like it's more likely to confuse people rather than be helpful for any projects. I'd like to remove them, but wanted to check that no one sees any value in preserving them before I made a change.

**Comment by afontani** [comment]
ResStock currently uses: 
- Option=Electric Heat Pump, 50 gal, 3.45 UEF
- Option=Electric Heat Pump, 66 gal, 3.35 UEF

Current options in options_lookup.tsv
- Electric Heat Pump, 50 gal
- Electric Heat Pump, 50 gal, 3.45 UEF
- Electric Heat Pump, 66 gal, 3.35 UEF
- Electric Heat Pump, 80 gal
- Electric Heat Pump, 80 gal, 3.45 UEF

@jmaguire1 : Are you referring to the "Electric Heat Pump, 50 gal" and "Electric Heat Pump, 80 gal" options? Are you saying these options are not relevant because they also don't represent any market penetration?

**Comment by afontani** [comment]
After the conversation in the ResStock Development meeting, we are going to move ahead and remove these items from options_lookup.tsv.
