### ISSUE TITLE
Confusion of floor area

### ISSUE THREAD

**Issue by afontani** [NREL/resstock#1273]
Right now ResStock uses AHS for floor area, updated in [this](https://github.com/NREL/resstock/pull/978) PR. This floor area is closer to the "assessed" floor area. The input to OS-HPXML is the conditioned floor area (https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#hpxml-building-construction). Here is some evidence below where the AHS floor area is closer to the RECS energy consuming area and larger than the maximum heated and cooled floor area.
![Screenshot 2024-07-16 at 4 19 22 PM](https://github.com/user-attachments/assets/d662f139-b1ff-4c68-92b5-8e5a07b9d7ca)

We have decided to use RECS 2020 data for the assigned values in ResStockArguments: https://github.com/NREL/resstock/blob/develop/measures/ResStockArguments/measure.rb#L409-L444.

A later item would be to introduce some randomness to the floor area bins. I generally have not liked that we use a single floor area for a bin.  In the results.csv we report the simulated floor area, so some randomization wouldn't obscure the results too much or hide anything from the user. 

Another change could be to move to RECS 2020 floor area distributions, but this would be a larger change and review of the results would be much more rigorous.

**Comment by rajeee** [comment]
Few additional issues I found while following up on this:
In RECS 2020, [we assume](https://github.com/NREL/resstock-estimation/blob/c0b54b829a873783f01cadba479cdbd2ad58e75a/sources/recs/recs2020/parameter_option_maps.py#L2658) that floor area is given by TOTSQFT_EN minus the area of garage for all homes. This is actually not correct. TOTSQFT_EN includes the area of the garage only if the garage is heated or cooled. We should account for that. RECS 2020 does provide a field to indicate whether the garage is heated/cooled, so we should be able to easily account for that.

In RECS 2009 (we still use RECS 2009 for several of our TSVs),[ we assume](https://github.com/NREL/resstock-estimation/blob/c0b54b829a873783f01cadba479cdbd2ad58e75a/sources/recs/recs2009/parameter_option_maps.py#L200) that the floor area is given by the maximum of ("TOTHSQFT", "TOTCSQFT"). Not only is this inconsistent with how we do it in REC2020, it also suffers from the same issue that "TOTHSQFT" and "TOTCSQFT" may or may not include the garage area depending upon whether the garage is heated/cooled. 

Since the floor area bin is supposed to be indicative of total conditioned floor area (aside from the garage), for both RECS2020 and RECS2009, we should switch to using TOTSQFT_EN if garage is neither heated nor cooled, and TOTSQFT_EN - garage_area if the garage is either heated or cooled.

**Comment by afontani** [comment]
A couple of data-points:
- National Average Conditioned Floor Area Before (v1): 1,651 sqft
- National Average Conditioned Floor Area After (v2): 1,490 sqft
- AHS 2023 Mean: 1,784 sqft
- RECS 2020 MAX(TOTHSQFT,TOTCSQFT): 1667 sqft
- RECS 2020 MAX(TOTHSQFT,TOTCSQFT) minus heating/cooled garage: 1648 sqft
- RECS 2020 TOTENSQFT: 1,819 sqft
- RECS 2020 TOTENSQFT minus heating/cooled garage: 1,799 sqft

A summary table of what spaces are included in various sources:
![Screenshot 2024-10-01 at 1 50 27 PM](https://github.com/user-attachments/assets/dc27fe7f-fdd2-45e5-abe6-a42891e02c5c)
C = Conditioned, U=Unconditioned

**Comment by afontani** [comment]
The main differrence between what is in the TSVs and ResStock arguments is the inclusion of unconditioned basements in AHS. This would make the floor areas larger than expected according the the ANSI/RESNET/ICC 301 definition that OpenStudio-HPXML uses. Accounting for this change in ResStock resulted in a decrease of about 100 ft2 on average for ResStock. The floor area estimate was already close to what RECS 2020 says with removing heated and cooled garages. 

This information has led me to decide that since AHS is a self-reported survey and the ResStock floor area estimate is close to the RECS 2020 estimate with the AHS data, removing the unconditioned basement piece of the floor area is not warranted. 

I am closing this issue.
