### ISSUE TITLE
Confirm daylight saving working correctly

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#469]
Do schedules get "shifted" when they are captured in Schedule:File objects? Is there a way we can verify that daylight saving is properly shifting all schedules?

**Comment by shorowit** [comment]
Leap years too?

**Comment by joseph-robertson** [comment]
Probably. (Although I feel like I recall the documentation stating leap years are accounted for.)

**Comment by joseph-robertson** [comment]
```
   ** Warning ** GetCurrentScheduleValue: Schedule="LIGHTING_EXTERIOR" is a Schedule:File
   **   ~~~   ** ...Use of Schedule:File when DaylightSavingTime is in effect is not recommended.
   **   ~~~   ** ...1) Remove RunperiodControl:DaylightSavingTime object or remove DST period from Weather File.
   **   ~~~   ** ...2) Configure other schedules and Schedule:File to account for occupant behavior during DST.
   **   ~~~   ** ...   If you have already done this, you can ignore this message.
   **   ~~~   ** ...When active, DaylightSavingTime will shift all scheduled items by one hour, retaining the same day type as the original.
```

**Comment by joseph-robertson** [comment]
@rajeee are you able to summarize your findings here? Or are you still investigating?

**Comment by rajeee** [comment]
So, after some testing and reading up, here is what I figured out:
If the Daylight saving time starts on 4/7 and ends on 10/26, here is how EnergyPlus will shift the input schedule file.
 
Up until hour ending midnight of 4/6 (just before beginning of 4/7), schedules are as it is. The first hour of 4/7 will be assigned the schedule value from the second hour of 4/7 (one hour shifting).

![image](https://user-images.githubusercontent.com/12487392/94053485-a0ed0b80-fd97-11ea-8aa5-6f5465fb1ba0.png)

 (The image shows how a scheduleFile containing values form 0.0001 to 0.8760 was applied by Energy+. The values on the screenshot is output by adding "Schedule Value" to the output variable)

This one hour shifting continues until the end of daylight saving period on 10/26.  The hour ending midnight of 10/26 will be assigned the schedule from the original first hour of 10/27.  The first hour of 10/27 will also be assigned the same schedule because the daylight savings has already ended by 10/27.
![image](https://user-images.githubusercontent.com/12487392/94053527-ae09fa80-fd97-11ea-8d90-cebd224997ff.png)


Anyway, all this is to say is, it works as you would expect a daylight shifting to work (though not ideal because of duplication of one datapoint, and loss of one datapoint).
 
I was almost done adding in compensating shifting (in other direction) in the schedule generator so that after the Energyplus shifts it, would come back to original structure.
 
However, now I am realizing that, we actually want those shifting. When we are using the ATUS data based markov-chain simulation to generate the schedule, and when someone said they took a shower at 6:00 AM, it means it's 6:00 AM on their local time (i.e. daylight shifted time), so, Energyplus shifting it back one hour to align it with standard time makes sense and is the correct thing to do.
 
Conclusion: Do nothing about it. It's working as expected.

Other thoughts:
The Energyplus warning is fair. Typically, if you have a pregenerated 8760 values of schedules in a ScheduleFile object, those are likely to be contiguous 8760 hours of the year and thus would be in-sync with the standard time (without daylight shifting). So, the default shifting that energyplus does would mess things up; and that's what the warning is about.

In our case though, the 8760s are based on local daylight saving times, and the shifting is appropriate. So, I think, we are okay. 

The implication is also that going forward, daylight saving times must always be supplied, otherwise the schedules would be incorrect.

**Comment by ejhw** [comment]
@rajeee Can this be closed because of your recent fix or is this a different issue?

**Comment by rajeee** [comment]
@ejhw Yeah, I think this can be closed, but not really because of the recent fix. It's a different issue regarding how EnergyPlus is handling the ScheduleFiles when DST is active.

**Comment by ejhw** [comment]
"Conclusion: Do nothing about it. It's working as expected"
