### ISSUE TITLE
Add generic multiplier argument to infiltration options to facilitate % reductions in ACH50

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#629]
With ~20 options for ACH50, we can end up with a proliferation of hundreds of yaml upgrades, especially if we have packages of measures that reduce ACH50 by different amounts (storm windows and insulated siding). 

Would it be a good idea to add a generic multiplier argument to infiltration options to facilitate % reductions in ACH50? It would default to 100% and we could have rows in options_lookup that just set the infiltration multiplier (so independent of ACH50 options).

cc @joseph-robertson @shorowit @afontani @ekpresent @munank

**Comment by shorowit** [comment]
This sounds similar to the remaining item from https://github.com/NREL/resstock/issues/42, except that example is attic insulation R-value instead of ACH50. I don't think we need an additional argument to achieve this. We just need to define a new [cost multiplier type](https://github.com/NREL/resstock/blob/935faeed8565c01c7a4651a9695c46c35302fac4/measures/SimulationOutputReport/measure.rb#L70-L86) -- e.g., "Infiltration Reduction (%)" or whatever.

Then:
- Current ResStock: When the ResidentialAirflow measure is called as part of the upgrade, calculate the percent reduction in infiltration and store it in the OSM using `additionalProperties`. Retrieve it when cost multipliers are calculate in the SimulationOutputReport measure.
- ResStock-HPXML: In the UpgradeCosts measure, calculate the reduction in infiltration by parsing both the baseline HPXML and upgrade HPXML.

**Comment by ejhw** [comment]
Cool idea. Seems like it could be confusing to users to rely on the cost multiplier, as opposed to options/arguments, to modify the model, but I'm open to trying it.

**Comment by shorowit** [comment]
I'm not sure what you mean. It seems to me that the user would have to choose the correct cost multiplier in both situations. (And is no different than a user having to choose a wall cost multiplier when they are defining up a wall upgrade.)

**Comment by ejhw** [comment]
My issue was not just about cost multipliers, but rather about model articulation. Check out @ekpresent 's yaml: https://github.com/NREL/resstock/blob/9d2dda8c243bd2855bb0868cbbc7550fda2231cc/facades-project-file-test10No3.yml#L1164

**Comment by ekpresent** [comment]
I think it is an extremely elegant yaml under the circumstances.

**Comment by shorowit** [comment]
> My issue was not just about cost multipliers, but rather about model articulation.

Ah, sorry, I didn't understand that. My proposal above was only to address cost multipliers.

**Comment by ekpresent** [comment]
Was speaking with @afontani today and this came up again. He suggested a tsv of infiltration multipliers, similar to the above suggestion. Would the HPXML workflow allow for such a thing if we implemented it?

**Comment by shorowit** [comment]
I wouldn't think a tsv of infiltration multipliers is needed if we're just talking about upgrades, since tsvs are used to describe the existing housing stock. 

Just need to add rows to options_lookup.tsv and then make sure the infiltration multipliers are handled during the model generation. This would be pretty trivial to accomplish w/ ResStock-HPXML by using the new [ResStock Arguments measure](https://github.com/NREL/resstock/tree/restructure-v3/measures/ResStockArguments), which allows pre-processing of inputs before they are passed to the BuildResidentialHPXML measure.

**Comment by ejhw** [comment]
@shorowit Wouldn't you need a new TSV (it would just be 100% 1.0 multiplier) if you wanted to separate the options for infiltration multipliers from the options with base infiltration arguments? Otherwise you'd still need a proliferation of options in options_lookup, right?
