### ISSUE TITLE
ResStock-HPXML: New features, training resources, etc.

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#796]
Checklist:
- [x] Changes to the buildstockbatch yml
- [x] New features that are enabled (e.g., secondary heating systems)
- [x] How to debug (use local `workflow/run_analysis.rb`?)
- [x] Taking advantage of new CI testing framework
- [x] Show `develop` vs `restructure-v3` comparisons
- [ ] Get feedback before we merge `restructure-v3`?

**Comment by joseph-robertson** [comment]
New Features:
- [ ] Rim joist modeling
- [ ] More options for:
  - [ ] foundation types?
  - [ ] foundation wall types?
  - [ ] roof types?
  - [ ] wall types?
  - [ ] fuel types?
  - [ ] efficiency units?
  - [ ] heat pump backup types?
  - [ ] duct leakage units?
  - [ ] duct locations?
  - [ ] mech vent fan types?
- [ ] More heating/cooling system types
  - [ ] E.g., stove, evaporative cooler, PTAC
- [ ] Partial space conditioning
- [ ] Secondary heating, mechanical ventilation systems
- [ ] Installation faults
  - [ ] Airflow, charge defect
- [ ] Whole house fan modeling?
- [ ] Water heater types?
  - [ ] Combi
- [ ] Drain water heat recovery?
- [ ] Battery modeling
- [ ] Emissions calculations
- [ ] Smooth schedules

@ejhw @shorowit @aspeake

**Comment by shorowit** [comment]
Note that some of these are new modeling features allowed by OS-HPXML but not necessarily used by ResStock-HPXML by default.

Aside from new modeling features, other benefits are A) speed (can we quantify this?), B) more consistency of modeling/assumptions with other applications (HEScore, ERI, WAP, etc.), and C) easier inspection of the building/model (HPXML inputs instead of E+ inputs).

**Comment by joseph-robertson** [comment]
[ResStock-HPXML](https://github.com/NREL/resstock/files/7974468/resstock-hpxml-demo.pptx)
