### ISSUE TITLE
Subtree buildstockbatch into resstock?

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#939]
Perhaps would help to alleviate version issues between the two.

**Comment by joseph-robertson** [comment]
This probably wouldn't solve the issue of someone activating a pre-built (old) version of buildstockbatch on eagle.

**Comment by rajeee** [comment]
Maybe also sub-tree restock-estimation while we are at it!

**Comment by afontani** [comment]
@nmerket, @joseph-robertson, and I ave decided to do the following instead of subtreeing buildstockbatch into resstock:
- Include ResStock integration test in buildstockbatch at the resstock develop branch.
- Point the resstock develop branch to a specific release of buildstockbatch. This way projects that branch off of resstock will be tied to a specific release of buildstockbatch.
- Have more regular releases of buildstockbatch
- Increment the resstock develop branch to new releases of buildstockbatch when they become available.

As a result, this issue can be closed.
